# Generated by Django 3.1.4 on 2021-04-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('uploaded_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'audiobook',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('name_of_the_song', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('uploaded_time', models.DateTimeField()),
                ('host', models.CharField(max_length=100)),
                ('participants', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'podcast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('name_of_the_song', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('uploaded_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'song',
                'managed': False,
            },
        ),
    ]
